# lang.py — i18n for OLED UI (EN/RU/RO)

_S = {
    "en": {
        "car": "CAR",
        "you": "YOU",
        "armed": "ARMED",
        "disarmed": "DISARMED",
        "listening": "Listening...",
        "sending": "Sending...",
        "confirm": "Confirm...",
        "response": "Response...",
        "requesting": "Request...",
        "no_answer": "NO ANSWER",
        "car_offline": "Car offline?",
        "no_radar": "No radar!",
        "sleeping": "Sleeping...",
        "radar_idle": "Radar idle",
        "shock_alarm": "Shock alarm",
        "radar_wake": "Radar wake",
        "tx_error": "TX error",
        "offline": "Offline",
        "default_cfg": "Default WiFi",
        "from_fob": "From fob",
        "signal_sent": "Signal sent",
        "sos_car": "SOS from car!",
        "emergency": "EMERGENCY!",
        "checking": "Checking...",
        "see_console": "See console",
        "rx_cmd": "RX cmd...",
        "sos_sent": "SOS SENT!",
        "wait": "WAIT",
        "listen": "LISTEN",
        "sleep": "SLEEP",
        "alarm": "ALARM!",
        "ping": "PING",
        "arm": "ARM",
        "zzzz": "Zzzz...",
        "clear": "Clear",
        "moving": "Moving",
        "still": "Still",
        "movstat": "Mov+Stat",
        "both": "Both",
        "vibr": "Vibr!",
        "no_rdr": "NoRdr",
        "none": "None",
        "bat": "Bat",
        "pkt": "Pkt",
        "rx_lbl": "RX",
        "lost_lbl": "L",
        "days": ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
        "no_link": "No link",
        "msg_Heartbeat": "Heartbeat",
        "msg_Status": "Status",
        "msg_Armed": "Armed",
        "msg_Disarmed": "Disarmed",
    },
    "ru": {
        "car": "АВТО",
        "you": "ТЫ",
        "armed": "ОХРАНА",
        "disarmed": "СНЯТО",
        "listening": "Слушаю...",
        "sending": "Отправка..",
        "confirm": "Ожидание..",
        "response": "Ответ...",
        "requesting": "Запрос...",
        "no_answer": "НЕТ ОТВЕТА",
        "car_offline": "Авто оффлайн",
        "no_radar": "Нет радара!",
        "sleeping": "Засыпаю...",
        "radar_idle": "Радар тихо",
        "shock_alarm": "Вибрация!",
        "radar_wake": "Радар!",
        "tx_error": "Ошибка TX",
        "offline": "Оффлайн",
        "default_cfg": "WiFi станд.",
        "from_fob": "От брелка",
        "signal_sent": "Сигнал послан",
        "sos_car": "SOS от авто!",
        "emergency": "ТРЕВОГА!",
        "checking": "Проверка..",
        "see_console": "См. консоль",
        "rx_cmd": "Команда...",
        "sos_sent": "SOS послан!",
        "wait": "ЖДИТЕ",
        "listen": "ПРИЁМ",
        "sleep": "СОН",
        "alarm": "ТРЕВОГА!",
        "ping": "ЗАПРОС",
        "arm": "ОХРАНА",
        "zzzz": "Засыпаю...",
        "clear": "Чисто",
        "moving": "Движение",
        "still": "Стоит",
        "movstat": "Дв+Ст",
        "both": "Оба",
        "vibr": "Вибр!",
        "no_rdr": "НетРад",
        "none": "Нет",
        "bat": "Бат",
        "pkt": "Пкт",
        "rx_lbl": "Пр",
        "lost_lbl": "П",
        "days": ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
        "no_link": "Нет связи",
        "msg_Heartbeat": "Пульс",
        "msg_Status": "Статус",
        "msg_Armed": "Охрана",
        "msg_Disarmed": "Снято",
    },
    "ro": {
        "car": "AUTO",
        "you": "TU",
        "armed": "ARMAT",
        "disarmed": "DEZARMAT",
        "listening": "Ascult...",
        "sending": "Trimit...",
        "confirm": "Confirm...",
        "response": "Raspuns...",
        "requesting": "Cerere...",
        "no_answer": "FARA RASP.",
        "car_offline": "Masina off?",
        "no_radar": "Fara radar!",
        "sleeping": "Adorm...",
        "radar_idle": "Radar liniste",
        "shock_alarm": "Vibratii!",
        "radar_wake": "Radar semnal",
        "tx_error": "Eroare TX",
        "offline": "Offline",
        "default_cfg": "WiFi implicit",
        "from_fob": "De la cheie",
        "signal_sent": "Semnal trimis",
        "sos_car": "SOS de la auto",
        "emergency": "URGENTA!",
        "checking": "Verificare..",
        "see_console": "Vezi consola",
        "rx_cmd": "Comanda...",
        "sos_sent": "SOS TRIMIS!",
        "wait": "ASTEPT",
        "listen": "ASCULT",
        "sleep": "SOMN",
        "alarm": "ALARMA!",
        "ping": "CERERE",
        "arm": "ARMARE",
        "zzzz": "Adorm...",
        "clear": "Liber",
        "moving": "Miscare",
        "still": "Static",
        "movstat": "Mi+St",
        "both": "Ambele",
        "vibr": "Vibr!",
        "no_rdr": "FaraRd",
        "none": "Nimic",
        "bat": "Bat",
        "pkt": "Pkt",
        "rx_lbl": "RX",
        "lost_lbl": "L",
        "days": ["Lu", "Ma", "Mi", "Jo", "Vi", "Sa", "Du"],
        "no_link": "Fara semnal",
        "msg_Heartbeat": "Puls",
        "msg_Status": "Status",
        "msg_Armed": "Armat",
        "msg_Disarmed": "Dezarmat",
    },
}

_l = "en"

def set_lang(code):
    global _l
    _l = code if code in _S else "en"

def t(key):
    return _S.get(_l, _S["en"]).get(key, key)
